### ISSUE TITLE
handshake failed after deployment on cleverCloud

### ISSUE THREAD

**Issue by florianroulet** [CleverCloud/wemos-ws-led-backend#1]
Hi there ! 
Really happy to have this little kit ! IT works fine locally, but after deploying on CleverCloud, the wemos was not able to connect to the backend.
Locally, I flashed the wemos with my IP adress on 8080
On clever, I used the app url (even tryed with florianroulet-wemos.cleverapps.io domain name) on port 80, but the wemos cannot reach the app. I got a handshake failed on the serial monitor.

What am I missing to have this working on clever ?

Big Thanks !!!!

**Comment by urcadox** [comment]
Hello,

Hm that's weird, it should work. So, you set this, right?

```c
#define WEBSOCKET_HOST "florianroulet-wemos.cleverapps.io"
#define WEBSOCKET_PORT 80
```

**Comment by florianroulet** [comment]
OMG, tried again and it worked this time !!
thanks !
